### ISSUE TITLE
RainVID&SS dataset

### ISSUE THREAD

**Issue by bowen480** [sunsean21/Event-Aware-Video-Deraining#2]
Hello, I am very interested in your work, and how can i get the dataset RainVID&SS?
Thank you!

**Comment by bowen480** [comment]
Sorry, I note that how to download it. Thank you

**Comment by sunshangquan** [comment]
Hi, you could download it from https://pan.baidu.com/s/1zuGkbKzQjnliujqDMHl1og?pwd=q0r1#list/path=%2Fdataset_event_derain . I will also upload it on Google Drive today and update its link in ReadMe.

**Comment by bowen480** [comment]
Thank you！

**Comment by sunshangquan** [comment]
Hi, the google drive link is https://drive.google.com/drive/folders/1uXlk7WuI1md_vYeXQJBm3ctgmziu3-xO?usp=sharing
